services:
  - type: web
    name: pulsera-web
    env: php
    plan: free
    buildCommand: composer install --no-interaction --prefer-dist --optimize-autoloader
    startCommand: php artisan migrate --force && php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: pulsera-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: pulsera-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: pulsera-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: pulsera-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: pulsera-db
          property: password

databases:
  - name: pulsera-db
    plan: free
